version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
  
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:3001
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend


